### ISSUE TITLE
Pagination required after lazy loading removed by Craft

### ISSUE THREAD

**Issue by adamhenretty** [Dolphiq/craft-plugin-redirect#103]
Cant only view 50 redirects sorted by either Source, Destination, Type, Hit and Count, or using the search since Craft removed lazy loading in favour of pagination.

**Comment by LukePeters** [comment]
Seeing this same issue now myself (sorry, I know  that's not helpful).

**Comment by Willbv** [comment]
Not a solution but at the end of the URL you can put '/p2' to get through the pages. Might be useful until this gets fixed.

**Comment by Coysh** [comment]
Agreed - this is becoming a little annoying; any chance of a fix soon?

**Comment by mijewe** [comment]
Any update on this?

**Comment by emilyfitton** [comment]
+1 for a fix for this one please

**Comment by my2ter** [comment]
Hi,

Agreed annoying...

I don't have time right now but can someone make a Pull Request, all it needs is in `redirect/src/templates/redirects.twig:63`

```
{% block footer %}
    <div id="count-container" class="light flex-grow">&nbsp;</div>
{% endblock %}
```

I've only tested with Craft 3.7 but pretty sure it works at least from Craft 3.3

Cheers

**Comment by johanzandstra** [comment]
Thanks for the fix @dwheeldo I have merged this and will tag a new version later today
