### ISSUE TITLE
Internal Server Error viewing redirects in Craft 3.4.0.2

### ISSUE THREAD

**Issue by ryanmasuga** [Dolphiq/craft-plugin-redirect#108]
Redirect version 1.0.23

Updated a site to 3.4.0.2 and cannot access the `/admin/redirect` page in the Control Panel  - it generates an Internal Server Error. The log says: 
```
2020-01-29 14:04:39 [-][1][...][error][RuntimeException] craft\web\twig\TemplateLoaderException: Unable to find the template “_elements/indexcontainer” in "redirect/redirects" at line 57. in /.../vendor/craftcms/cms/src/web/twig/TemplateLoader.php:116
```
This plugin was working fine on this site before the update (Craft version 3.3.20.1). I blew away vendor folder and re-downloaded the whole thing; error still occurring.

**Comment by marcodewaard** [comment]
We've got the same issue on Craft v3.4.1.

**Comment by brandonkelly** [comment]
This is because the old `_elements/indexcontainer` template was removed in 3.4, but I’ll go ahead and bring it back for 3.4.2.

**Comment by brandonkelly** [comment]
Craft 3.4.2 is out now with that template brought back in.
