### ISSUE TITLE
How to redirect a path using wildcards?

### ISSUE THREAD

**Issue by oadslug** [Dolphiq/craft-plugin-redirect#118]
I looked through all the examples, but I'm not seeing a way to redirect a path using wildcards to account for additional segments. I apologize if I've missed something obvious.

I am trying to redirect:
    "oldcategory/any/number/of/additional/segments"
to:
    "newcategory/any/number/of/additional/segments"

I have tried:
    oldcategory/<options:.+>
    newcategory/<options:.+>

That doesn't seem to work. Are there other wildcard twig patterns? or can I use grep? 

Any help would be much appreciated. Thank you.

**Comment by alexroper** [comment]
I had the same question, but this plugin seems to be abandonware. This worked for me:

Source URL: 
`oldcategory/<options:.+>`

Destination URL: 
`newcategory/<options>`

You don't need to use the word "options" however. I used `<segments.+>`.
