### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by schmidtsonian** [Dolphiq/craft-plugin-redirect#123]
I can't install the plugin, this are the things I made so far:

I'm using Craft CMS 3.6.17

![image](https://user-images.githubusercontent.com/2094546/124029442-c3f9bb00-d9ba-11eb-80b9-aaa1e67de5d1.png)

full log: 
```
Error: /var/www/html/vendor/dolphiq/redirect does not exist and could not be created.

Composer output: Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file
Package operations: 1 install, 0 updates, 4 removals
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
```

Then I tried this: https://github.com/Dolphiq/craft3-plugin-redirect/blob/master/INSTALL.md but in the step 3 this happened:

![image](https://user-images.githubusercontent.com/2094546/124029744-120ebe80-d9bb-11eb-8dd2-d48a1b17db60.png)

Then I tried using craft cli:
```
./craft plugin/install dolphiq/redirect
```
but I got this error:

![image](https://user-images.githubusercontent.com/2094546/124029936-48e4d480-d9bb-11eb-9e2a-4376755e23e1.png)

then I made:
```
./craft plugin/install redirect
```

and I got this:

![image](https://user-images.githubusercontent.com/2094546/124030032-64e87600-d9bb-11eb-8c78-813a8c39d0ec.png)

but the plugin is still "not installed":

![image](https://user-images.githubusercontent.com/2094546/124030122-7a5da000-d9bb-11eb-9868-ce67ed122588.png)

this is my composer.json file:
```json
{
    "require": {
        "craftcms/aws-s3": "^1.2",
        "craftcms/cms": "^3.6.4",
        "craftcms/element-api": "^2.7",
        "craftcms/redactor": "^2.8",
        "dolphiq/redirect": "^1.1",
        "dolphiq/sitemap": "^1.3",
        "spicyweb/craft-neo": "2.9.11",
        "verbb/super-table": "^2.6",
        "vlucas/phpdotenv": "^3.4.0"
    },
    "require-dev": {
        "yiisoft/yii2-shell": "^2.0.3"
    },
    "autoload": {
        "psr-4": {
            "modules\\": "modules/",
            "normalize\\": "modules/normalize",
            "formsApi\\": "modules/formsApi"
        }
    },
    "config": {
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "7.2.5"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ]
    }
}
```

**Comment by dannyibishev** [comment]
My setup. 
- Craft CMS Pro 3.5.19.1
- Redirect Plugin: 1.1.1

@schmidtsonian  I found a workaround hack to the problem that will work as a temporary measure until the devs resolve it.

Retracing your steps. after running `./craft plugin/install redirect` I saw the same error where the database table `craft_dolphiq_redirects` already existed.

After dropping the table and re-running the command. The install successfully completed.

**Comment by schmidtsonian** [comment]
> My setup.
> 
> * Craft CMS Pro 3.5.19.1
> * Redirect Plugin: 1.1.1
> 
> @schmidtsonian I found a workaround hack to the problem that will work as a temporary measure until the devs resolve it.
> 
> Retracing your steps. after running `./craft plugin/install redirect` I saw the same error where the database table `craft_dolphiq_redirects` already existed.
> 
> After dropping the table and re-running the command. The install successfully completed.

I made the same thing at the end, thank you.
