### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by atimoda** [Dolphiq/craft-plugin-redirect#125]
Hi guys,

I'm getting internal server error when trying to access website if the plugin is activated and the setting "Activate redirects" is on.
If the plugin is disabled, or this setting turned off, then everything works fine.

Plugin version: 1.1.1
Craft CMS version: 3.7.18

The following error appears on the log. Any suggestion about the cause of this?
Thanks!

`yii\base\ErrorException: preg_match(): Compilation failed: quantifier does not follow a repeatable item at offset 1 in /var/www/vhosts/redemetamorfose.org/vendor/yiisoft/yii2/web/UrlRule.php:412
Stack trace:
#0 /var/www/vhosts/redemetamorfose.org/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(2, 'preg_match(): C...', '/var/www/vhosts...', 412)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'preg_match(): C...', '/var/www/vhosts...', 412, Array)
#2 /var/www/vhosts/redemetamorfose.org/vendor/yiisoft/yii2/web/UrlRule.php(412): preg_match('#^?p=eventos/03...', 'perfil/atimoda', NULL)
#3 /var/www/vhosts/redemetamorfose.org/vendor/craftcms/cms/src/web/UrlRule.php(80): yii\web\UrlRule->parseRequest(Object(craft\web\UrlManager), Object(craft\web\Request))
#4 /var/www/vhosts/redemetamorfose.org/vendor/craftcms/cms/src/web/UrlManager.php(426): craft\web\UrlRule->parseRequest(Object(craft\web\UrlManager), Object(craft\web\Request))
#5 /var/www/vhosts/redemetamorfose.org/vendor/craftcms/cms/src/web/UrlManager.php(359): craft\web\UrlManager->_getMatchedUrlRoute(Object(craft\web\Request))
#6 /var/www/vhosts/redemetamorfose.org/vendor/craftcms/cms/src/web/UrlManager.php(114): craft\web\UrlManager->_getRequestRoute(Object(craft\web\Request))
#7 /var/www/vhosts/redemetamorfose.org/vendor/craftcms/cms/src/web/Request.php(1325): craft\web\UrlManager->parseRequest(Object(craft\web\Request))
#8 /var/www/vhosts/redemetamorfose.org/vendor/yiisoft/yii2/web/Application.php(83): craft\web\Request->resolve()
#9 /var/www/vhosts/redemetamorfose.org/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest(Object(craft\web\Request))
#10 /var/www/vhosts/redemetamorfose.org/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /var/www/vhosts/redemetamorfose.org/public_html/index.php(22): yii\base\Application->run()
#12 {main}`

**Comment by johanzandstra** [comment]
HI @atimoda it looks like one of your url entries is not a valid preg_match. Please let me know if you still have this issue. For now I close this one.
