### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by angieherrera** [Dolphiq/craft-plugin-redirect#127]
Wondering if this plugin will get updated for Craft 4?

**Comment by CreateSean** [comment]
Also inquiring about a Craft 4 update?

**Comment by CreateSean** [comment]
This appears to be abandonware - guess it's time to figure out a migration strategy.

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3). If it gets enough votes, we'll migrate this plugin to Craft 4 and continue to work on it, giving it a new home, and keeping it open source.

Do let us know if you plan to make the plugin Craft 4 compatible!

**Comment by alexanderloewe** [comment]
I like the plugin. We use it in over 30 projects. We would love if you update it or verbb would take it over.

**Comment by Copula-tech** [comment]
+1 for Craft 4

**Comment by TUSAB-web** [comment]
I also use this plugin. It is very useful!

**Comment by mortendk** [comment]
+1 for a craft4

**Comment by bboy-splendid** [comment]
+1 would like this for Craft 4!

**Comment by khalwat** [comment]
Our [Retour](https://github.com/nystudio107/craft-retour) plugin is available for Craft 4, which also handles redirects.

Would anyone be interested in a migration path from this Redirects plugin to Retour?

**Comment by angieherrera** [comment]
@khalwat - absolutely!

**Comment by johanzandstra** [comment]
Hi Guys, Sorry for the late reply. I was so busy last few months. Just found some time to make the plugin compatible with php 8.0 and 8.1. Next to that the 2.0 version supports Craft 4.x now
