### ISSUE TITLE
Forward Slashes Removed on Save

### ISSUE THREAD

**Issue by DigitalRebelMarketing** [Dolphiq/craft-plugin-redirect#130]
When saving entry with a forward slash, the slashes are removed.  See screenshot and Craft info below.

![image](https://user-images.githubusercontent.com/80113931/201224804-18a6a2e4-5346-40c9-afd3-8e607e301ac1.png)
![image](https://user-images.githubusercontent.com/80113931/201225004-3cf27635-7328-4b36-a128-1493e8b8a35e.png)

**Comment by johanzandstra** [comment]
@DigitalRebelMarketing I hope the new version fixed this issue, please let me know if you still run into this issue.
