### ISSUE TITLE
Redirects are not editable since Craft 4.3.3

### ISSUE THREAD

**Issue by idleog** [Dolphiq/craft-plugin-redirect#131]
After updating to Craft 4.3.3, the link to edit redirect items has gone.

<img width="1817" alt="Bildschirm­foto 2022-11-22 um 11 16 29" src="https://user-images.githubusercontent.com/870071/203288515-c73df8cf-f698-49b8-bddf-dc39ea10371d.png">

**Comment by dr-codswallop** [comment]
Yep, me too. Just installed on Craft 4.3.3 and no options to edit any of the redirects

**Comment by amphibian** [comment]
Yup, same issue here. This happened with other plugins as well (I think Formie was one I saw it in) and they fixed it up very quickly. Also no way to delete redirects now.

**Comment by nrastam** [comment]
We face the same error.
Since editing a redirect is one of the core features of this plugin, we clearly need this to work again.

Hopefully it will be resolved soon! 🤞

**Comment by Maybach91** [comment]
Is there any plan to get this fixed / workarounded @johanzandstra @Mosnar ?

**Comment by MacroFabMktg** [comment]
Until it's fixed... you can follow these steps:

- Right Click on the item you wish to edit and select "inspect"
-  Get the ID from the <tr data-id="XXX"> tag row.
- Put the following in the URL: https://yourdomain.com/admin/redirect/{redirectID}?site={siteId}

You should be able to edit and save from there.

**Comment by pimago** [comment]
The workaround does not work for me. Also I need to delete some redirects. Has this plugin been abandoned?

**Comment by thomasbendl** [comment]
Same here with Craft CMS 4.3.4 - Is the fix in progress?

**Comment by gateszies** [comment]
Experiencing this same issue on Craft 4.3.5. We can create a new redirect but are not able to edit or delete any of the existing redirects.

**Comment by KBjana** [comment]
Experiencing the same issue on Craft 4.3.6.

**Comment by JoshC96** [comment]
I've created a fix for this in a new PR  https://github.com/Dolphiq/craft-plugin-redirect/pull/132

**Comment by johanzandstra** [comment]
Thanks @JoshC96 for the fix. I merged this fix and some other improvements into a new version 2.0.1. Please let me know if there are still troubles opening the redirects

**Comment by JoshC96** [comment]
I've made a fix for this and will create a new branch/PR for it now :) 

> 

Fantastic, thanks very much @johanzandstra
